### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by kaderavaclav** [norbertfabian/PA036Project#1]
@norbertfabian proč máme tak šílenou strukturu v src/main/java?

EDIT: konkrétně myslím tam to cz.muni.pa036 ...

**Comment by norbertfabian** [comment]
@kaderavaclav Zabehnutý zvyk. Učili ma tak v škole a význam to má napríklad vo chvíli, keď tých projektov budeš mať viac a chceš vedieť nejak efektívne medzi nimi pracovať. Predstav si napríklad, že by si mal všetky svoje projekty nahrané na jedno miesto a chceš nájsť všetky univerzitné projekty. Zadáš do vyhľadávania muni a máš ich. Všetky ich obsahujú ako package. Ak len z tohoto predmetu  všetky tak zadáš kód a máš. Tak isto by to mohlo mať zmysel niekde na store ak by si chcel hľadať projekty od rovnakej firmy. Je fakt, že by sme tento projekt zvládli aj bez nejakej hlbšiej hierarchie ale bezdôvodne nechcem zanedbávať dobré zvyky. Ak však budete trvať na zrušení tých package tak za mňa ok.

**Comment by 123tomas** [comment]
Ja na nicom netrvam, ja som zvyknuty podobne zo skolskych projektov:)

**Comment by kaderavaclav** [comment]
Už jsme to s @norbertfabian řešili na facebooku, přijde mi to zbytečné u toho typu projektu... zbytečnost, která to trochu semení... vzpomínám, že jsme právě díky takto pitomě složitě zvolené struktuře často dělali chyby v překlepech a dost to kde koho mátlo...je mi to ale jedno, jenom jsem chtěl vědět, jestli to nemá nějaký jiný extra význam pro vás :)
